### ISSUE TITLE
議事録

### ISSUE THREAD

**Issue by limit7412** [InfomationAndCommunicationsProject/Adventure#2]

**Comment by limit7412** [comment]
5/10
輪講について
　ゲーム仕様書の書き方
　https://www.slideshare.net/mobile/OsamuOhkubo/ver110-27105144

議事録
　最終制作
　　先生との面談(強制)
　　　アイデア　rpg?
　　　ドラクエっぽい?
　　　短くさくっと
　　　(最終制作の)資料作りながら
　　(短いrpgを作るならviprpgあたりが参考になるのでは)
　　正直一番熱意がある人が欠席で2人では決めかねる
　アドベンチャーゲーム
　　用意するもの:素材,シナリオ
　　検索して目に付いた有名所
　　　fate,シュタゲ,ハンサム学園,逆転裁判
　　　検索ではibとかも出てきたがこれはちょっと違うのでは?
　　クイズやミステリーはネタが...
　　(清書していてどの位の長さするかなども気になりました)

宿題
設計書の輪講　資料と準備
アドベンチャーゲームのシナリオ　アイデア
最終制作について　何をやりたいか

**Comment by ponJuice** [comment]
5/１７
- 議事録
  - 自由課題
    - ジャンル：RPG
    - 戦闘システム：ターン制
    - ワールドマップ：各拠点を点で表し、パスで結ぶ。移動は点をタッチすることによる
    - ストーリー重視
  - アドベンチャー
    - セーブ、ロード、スキップ機能の実装
- 宿題
  - 自由課題、あるいはアドベンチャーのアイデア
  - ゲームの設計書の資料準備

**Comment by ponJuice** [comment]
5/24
・議事録
世界観：ファンタジー
世界情勢：割と平和な中世　魔物がいるがたいした事ない
ストーリー：
師匠と山で二人で暮らしている主人公が、世界平和のために伝説の剣作る。
システム：
・世界各地に赴き、伝説の剣の素材を集め、自分の剣を強化していく
・魔法はなく、スキル制（剣技）
・防具はあり
・ラスボスを倒すと最後の素材が手に入り、エンディング

・宿題
データの構造を決定
戦闘システムのプロトタイプ作成
仕様書（戦闘システム）を書く

**Comment by ponJuice** [comment]
戦闘システム
・技の熟練度制
　⇒技を使い続けると、熟練度が上がり、新たな派生技を覚えられる。
　⇒基礎パラメータは、派生技の習得時に上がる。上げ率は要検討。

・敵のパラメータ
　⇒敵によってランク分けをする。
　⇒プレイヤーの習得した技の数によってパラメータを決める
　　⇒ランクによってプレイヤーに倒せるか倒せないかを判断させる。

・防具はいいパラメータの防具ほど高い

・お金
　⇒レベルの高いモンスター程、価値の高い素材を落とす。

**Comment by ChinTou** [comment]
議事録：
　adv　ゲーム　画像決め
　adv　の英語バージョン？
　自由製作について、技の連撃システムを考える。

**Comment by limit7412** [comment]
スケジュール
シューティング
6/28を目処に仕様を決める
7/5を目処にリソースを集める

自由製作仕様
6/28を目処に大まかに決める⇒陳
7/5を目処にリソースを集める⇒横山
6/28を目処にUnityで戦闘システムを作る⇒後藤

輪講
今日から少しずつはじめる

**Comment by limit7412** [comment]
6/28

物理演算の資料

ゲーム製作者のための物理シュミレーション剛体編

必要な説明
　物理演算とは
　モンキーハンティングとは　
　実際の実装の説明
　重力　衝突判定（丸と丸）　跳ね返り

A:スライド
C:プログラミング

発表前に一度集まる

**Comment by limit7412** [comment]
スライドに必要なもの
　1.タイトル(1枚)
    　⇒Epée de légende

　2.ゲーム概要(キャラクタ、ストーリーなど)(1、2枚)
　　　⇒主要登場人物,3名,主人公(男),考古学者(女),師匠(男)
　　　　各地のダンジョンで剣を強化していく

　3.注目点(1枚)
　　　⇒前回発表の面白いところ

　4.全体の流れ(1枚)
　　　　ADVパート⇒町(ショップ,ステータス,アイテム)⇔ダンジョン(5階層)⇒次のADV

　　　　 　オープニング⇒町1⇔       町2⇔............⇔町n
 　　　　             　             ↓　　       ↓      　　　　      ↓
　　　　　　　            ダンジョン1 ダンジョン2   ダンジョンn⇒エンディング

　5.ゲーム画面など具体的な構成(1〜3枚)
　　　⇒町,（ショップ,ステータス,アイテム）,ダンジョン,ボス,バトル
　　　　adv:背景,テキストボックス,ロゴ,セーブ
　　　　ステータス:パラメータの表示,装備変更,スキル
　　　　アイテム,ショップ
　　　　バトル:HP,モンスター,コマンド,

**Comment by limit7412** [comment]
戦闘システム
　チェーン
　レベルなし
　スキルを使うとそれが強化
　　　　⇒同時にステータス変化
　モンスター　レベルはないがランクで強さ
